#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Dec 27 12:53:24 -03 2023
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim fir_tb_behav -key {Behavioral:sim_1:Functional:fir_tb} -tclbatch fir_tb.tcl -log simulate.log"
xsim fir_tb_behav -key {Behavioral:sim_1:Functional:fir_tb} -tclbatch fir_tb.tcl -log simulate.log

